# action.yml
name: 'Redmine Integration'
description: 'update redmine issue'
author: 'thaim'
branding:
  icon: 'git-pull-request'
  color: 'red'
inputs:
  token:
    description: 'github token'
    required: true
    default: ${{ github.token }}
  redmine_host:
    description: 'redmine hostname to integrate with'
    required: true
  redmine_apikey:
    description: 'redmine apikey to use'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
